name: The Americans
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6055686064064503
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dce0e3'
    - '#aab1b7'
    - '#25242a'
    - '#5a5a5c'
    - '#b8846f'
  brandStrength: 0.375
  lightness: 0.08573892549611628
  saturation: 0.6945175644941628
  rhythmicContrast: 0.9268113330472261
purpose: []
